# ── Stage 1: build ───────────────────────────────────────────────────────────
# Note: coverage-matrix.json is pre-generated by `make` before docker build.
# This avoids needing test files in the Docker context (.dockerignore excludes tests/).
FROM node:22-alpine AS build
WORKDIR /app

COPY void42-ca.crt /usr/local/share/ca-certificates/void42-ca.crt
RUN apk add --no-cache ca-certificates && update-ca-certificates
ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/void42-ca.crt

COPY package*.json .npmrc ./
RUN npm ci

COPY . .
RUN npm run build

# ── Stage 2: serve ────────────────────────────────────────────────────────────
FROM nginx:1.29
COPY --from=build /app/dist /usr/share/nginx/html
COPY rate-limit.conf /etc/nginx/conf.d/00-rate-limit.conf
COPY nginx.conf /etc/nginx/templates/default.conf.template
ENV POD_NAMESPACE=gmr
