apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: gmr-web
  labels:
    app: gmr-web
spec:
  replicas: {{ .Values.replicas | default 1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gmr-web
  template:
    metadata:
      labels:
        app: gmr-web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: nginx
          image: "contribute.void42.internal/golden/gmr-web:{{ .Values.version }}"
          imagePullPolicy: Always
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
          volumeMounts:
            - name: umami-config
              mountPath: /usr/share/nginx/html/umami-config.js
              subPath: umami-config.js
              readOnly: true
      volumes:
        - name: umami-config
          configMap:
            name: gmr-web-umami-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
