apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gmr-web
  namespace: gmr
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: gmr.void42.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gmr-web
                port:
                  number: 80
