apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gmr-web
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.entrypoints | default "web" | quote }}
    {{- if .Values.tlsRedirect }}
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-to-https@kubernetescrd
    {{- end }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gmr-web
                port:
                  number: 80
