apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: fontem-web
  labels:
    app: fontem-web
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: fontem-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      {{- if eq .Values.serviceType "NodePort" }}
      nodePort: 31147
      {{- end }}
      protocol: TCP
