apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: gmr-web
  labels:
    app: gmr-web
spec:
  type: {{ .Values.serviceType | default "NodePort" }}
  selector:
    app: gmr-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      {{- if eq (.Values.serviceType | default "NodePort") "NodePort" }}
      nodePort: 31147
      {{- end }}
      protocol: TCP
