apiVersion: v1
kind: Service
metadata:
  namespace: gmr
  name: gmr-web
  labels:
    app: gmr-web
spec:
  type: NodePort
  selector:
    app: gmr-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31147
      protocol: TCP
